### ISSUE TITLE
Add update_password option

### ISSUE THREAD

**Issue by jkirk** [robertdebock/ansible-role-users#10]
**Is your feature request related to a problem? Please describe.**
When setting a password for a user (on creation) we usually don't want to revert the password once it was changed.

**Describe the solution you'd like**
The Ansible user module has an `update_password` parameter which allows to only set the password `on_create`. It would be nice if we could add this option in [`user.yml`](https://github.com/robertdebock/ansible-role-users/blob/4a46c93de2aae5ebde773b393b36aabdb7ca2edf/tasks/user.yml#L4).
I am not sure if we should default to `always` though, I would vote for `on_create`, but I would like to hear your opinon.

**Comment by robertdebock** [comment]
Good suggestion and looks like it's easy to implement. Thanks @jkirk!

**Comment by robertdebock** [comment]
This has been implemented and released.
