### ISSUE TITLE
Refactor role for real idempotence and enhance users and ssh key features

### ISSUE THREAD

**Issue by rembik** [robertdebock/ansible-role-users#2]
**Is your feature request related to a problem? Please describe.**
Currently there is no real idempotence for adding cron.allow and bootstrapping in general.
Furthermore there is no support for managing users and multiple ssh keys over time.

**Describe the solution you'd like**
* add support for bootstrap remote user
* add support for more Ansible user attributes
* add support for multiple authorized ssh keys per user
* add management features for users and ssh keys (create & delete)
* add support for openssh password authentication configuration (optional)
* add real test case to playbooks

**Describe alternatives you've considered**
None.

**Additional context**
[![Build Status](https://travis-ci.org/rembik/ansible-role-users.svg?branch=master)](https://travis-ci.org/rembik/ansible-role-users)
[GitHub Fork](https://github.com/rembik/ansible-role-users)

**Comment by robertdebock** [comment]
Cool, I've been reworking this role too, there are quite a few flaws in it.

We're probably going to have merge conflicts, but your help is appreciated!

**Comment by rembik** [comment]
Yeah, thats why I dont create a pull request. My work has major changes and I think you would not merge it because it is backwards incompatible. Maybe you can adapt a bit.

**Comment by robertdebock** [comment]
The role is stable after the [last release](https://github.com/robertdebock/ansible-role-users/releases).

Let's go over the list of this you want in implement:

- add support for bootstrap remote user
- add support for more Ansible user attributes
- add support for multiple authorized ssh keys per user
- add management features for users and ssh keys (create & delete)
- add support for openssh password authentication configuration (optional)
- add real test case to playbooks

I'm a bit skeptic towards a mass-merge; it's more difficult to understand, test and release.

How do you want to approach this? Shall I "steal" parts of you code and integrate it here?

**Comment by robertdebock** [comment]
In the latest release I've implemented:

- add support for multiple authorized ssh keys per user
- add real test case to playbooks

Todo:
- add support for bootstrap remote user
- add support for more Ansible user attributes
- add management features for users and ssh keys (create & delete)
- add support for openssh password authentication configuration (optional)

**Comment by tlc** [comment]
How about setting the user's shell?

shell: "{{ user.shell | default('/bin/bash') }}"

**Comment by robertdebock** [comment]
Great plan @robertdebock, I've changed the code for this:

```
shell: "{{ user.shell | default(omit) }}"
```

The `omit` does not set a shell when it's not defined. This ensures the systems default shell (likely `/bin/bash`) is picked.

I'll try to do a release soon.
