### ISSUE TITLE
Make role work well with usernames containing a '.' (dot) sign.

### ISSUE THREAD

**Issue by piotrekzurek** [robertdebock/ansible-role-users#23]
## Proposed feature

Make role work well with usernames containing a '.' (dot) sign. 
Currently it doesn't work for such users.

## Rationale

This is from sudoers(5) manual:

>      The #includedir directive can be used to create a sudoers.d directory that the system package manager can drop sudoers file rules into as part of package installation.  For example, given:

         #includedir /etc/sudoers.d

     sudo will suspend processing of the current file and read each file in /etc/sudoers.d, skipping file names that end in ‘~’ or contain a ‘.’ character to avoid causing problems with package manager or editor temporary/backup
     files.  Files are parsed in sorted lexical order.  That is, /etc/sudoers.d/01_first will be parsed before /etc/sudoers.d/10_second.  Be aware that because the sorting is lexical, not numeric, /etc/sudoers.d/1_whoops would be
     loaded after /etc/sudoers.d/10_second.  Using a consistent number of leading zeroes in the file names can be used to avoid such problems.  After parsing the files in the directory, control returns to the file that contained the
     #includedir directive.

## Additional context
I'll do some code changes right away with a PR.

**Comment by robertdebock** [comment]
Closing this issue, as the PR was merged.
