### ISSUE TITLE
Remove sudo options for user if user.sudo_options is not defined

### ISSUE THREAD

**Issue by jkirk** [robertdebock/ansible-role-users#7]
**Describe the bug**
When `user.sudo_options` is removed, `/etc/suders.d/{{ user.name }}` is not removed.

**Expected behavior**
When `user.sudo_options` is removed, we should make sure that `/etc/suders.d/{{ user.name }}` is removed.

**Environment**
- Control node: Debian 9 (Debian/stretch)
- Control node Ansible version: 2.8.0
- Managed node OS: Debian 9 (Debian/stretch)

**Comment by robertdebock** [comment]
Fair point. I'll work on a fix, thanks for the feedback!
