### ISSUE TITLE
local ssh_key_directory is created on every ansible (check) run

### ISSUE THREAD

**Issue by jkirk** [robertdebock/ansible-role-users#8]
**Describe the bug**
Every (check) run of this role triggers a change at the task "create local ssh_key_directory".
The directory should either only be created when needed or should not trigger a change. (I prefer the former, but discussion welcome..  :wink:)

**To Reproduce**
```
% ansible-playbook -D -C site.yml
[...]
TASK [robertdebock.users : create local ssh_key_directory] 
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "ssh_keys",
-    "state": "absent"
+    "state": "directory"
 }

changed: [site.example.com]
[...]
```

**Expected behavior**
A change should not be triggered.

**Environment**
- Control node OS: Debian 9 (Debian/stretch)
- Control node Ansible version: 2.8.0
- Managed node OS: Debian 9 (Debian/stretch)

**Comment by robertdebock** [comment]
I'll have a look, thanks!

**Comment by robertdebock** [comment]
I tried to reproduce this, but am having difficulties. The molecule tests include idempotence checks and they pass.

Can you show me the playbook you are using?

**Comment by robertdebock** [comment]
If I re-read this; the task `create local ssh_key_directory` should be changed when it does not exist, either check_mode or not.

Closing.
