### ISSUE TITLE
'create local ssh_key_directory' should be optional?

### ISSUE THREAD

**Issue by AlexP11223** [robertdebock/ansible-role-users#9]
As I understand `ssh_key_directory` is used to store the generated ssh keys. If I don't want to generate the keys (e.g. provide already existing keys) this directory should not be created.

**Comment by robertdebock** [comment]
Hi @AlexP11223, thanks. You are correct. I'll write a fix for this.

**Comment by robertdebock** [comment]
This has been implemented, forgot to get back to you. Sorry.
